2024-01-25 13:30:36.761 | INFO     | backend.settings:<module>:189 - base.py settings loading
2024-01-25 13:30:39.987 | INFO     | business.urls:<module>:24 - Start to watch log file
2024-01-25 13:30:39.991 | INFO     | business.urls:<module>:35 - LOG_PATH监控线程已启动，LOG_PATH: D:/LibCity/Bigscity-LibCity\libcity\log\
2024-01-25 13:38:40.986 | INFO     | business.views:perform_create:93 - 已接受到文件，正在进行处理，文件名: Seattle.zip
2024-01-25 13:38:40.991 | INFO     | business.views:perform_create:116 - 存储到服务器上的临时文件路径：C:\Users\King.xx\AppData\Local\Temp\fb8nftxt.upload.zip 正在把此文件复制到 raw_data 目录中：D:/LibCity/Bigscity-LibCity\raw_data\3_Seattle.zip
2024-01-25 13:38:41.034 | INFO     | business.views:perform_create:128 - 文件上传完毕，文件名: 3_Seattle
2024-01-25 13:40:34.050 | INFO     | business.views:perform_create:93 - 已接受到文件，正在进行处理，文件名: Seattle.zip
2024-01-25 13:40:34.051 | INFO     | business.views:dataset_duplication_handle:895 - 文件重复，文件路径：D:/LibCity/Bigscity-LibCity\raw_data\3_Seattle.zip
2024-01-25 13:40:53.325 | INFO     | business.views:perform_create:93 - 已接受到文件，正在进行处理，文件名: Seattle - 副本.zip
2024-01-25 13:40:53.327 | INFO     | business.views:perform_create:116 - 存储到服务器上的临时文件路径：C:\Users\King.xx\AppData\Local\Temp\rki08_x3.upload.zip 正在把此文件复制到 raw_data 目录中：D:/LibCity/Bigscity-LibCity\raw_data\3_Seattle - 副本.zip
2024-01-25 13:40:53.355 | INFO     | business.views:perform_create:128 - 文件上传完毕，文件名: 3_Seattle - 副本
2024-01-25 13:43:11.929 | INFO     | business.threads:run:33 - start execute task, backup_dir: D:\LibCity\Bigscity-LibCity-WebTool-master\smartcityms_backend
2024-01-25 13:43:11.931 | INFO     | business.threads:run:36 - change dir: D:\LibCity\Bigscity-LibCity
2024-01-25 13:43:11.960 | INFO     | business.threads:run:51 - execute command: python run_model.py --exp_id 26238 --task map_matching --model HMMM --dataset 3_Seattle --saved_model True --train True --max_epoch 1 --gpu False --gpu_id 0
2024-01-25 13:43:11.984 | INFO     | common.utils:execute:99 - 命令执行进程启动，进程号: 22784
2024-01-25 13:43:21.998 | INFO     | common.utils:execute:104 - 实验已结束，状态码：1
2024-01-25 13:43:22.007 | ERROR    | common.utils:execute:114 - [ERROR] command: python run_model.py --exp_id 26238 --task map_matching --model HMMM --dataset 3_Seattle --saved_model True --train True --max_epoch 1 --gpu False --gpu_id 0; message: Traceback (most recent call last):
  File "run_model.py", line 7, in <module>
    from libcity.pipeline import run_model
  File "D:\LibCity\Bigscity-LibCity\libcity\pipeline\__init__.py", line 1, in <module>
    from libcity.pipeline.pipeline import run_model, hyper_parameter, objective_function
  File "D:\LibCity\Bigscity-LibCity\libcity\pipeline\pipeline.py", line 2, in <module>
    from ray import tune
  File "D:\Anaconda3\envs\LibCity\lib\site-packages\ray\__init__.py", line 63, in <module>
    import ray._raylet  # noqa: E402
  File "python\ray\_raylet.pyx", line 102, in init ray._raylet
  File "D:\Anaconda3\envs\LibCity\lib\site-packages\ray\exceptions.py", line 7, in <module>
    from ray.core.generated.common_pb2 import RayException, Language, PYTHON
  File "D:\Anaconda3\envs\LibCity\lib\site-packages\ray\core\generated\common_pb2.py", line 33, in <module>
    _descriptor.EnumValueDescriptor(
  File "D:\Anaconda3\envs\LibCity\lib\site-packages\google\protobuf\descriptor.py", line 789, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

2024-01-25 13:43:22.020 | INFO     | business.threads:run:158 - execute completed! change path to: D:\LibCity\Bigscity-LibCity-WebTool-master\smartcityms_backend
2024-01-25 13:48:04.911 | INFO     | business.threads:run:33 - start execute task, backup_dir: D:\LibCity\Bigscity-LibCity-WebTool-master\smartcityms_backend
2024-01-25 13:48:04.914 | INFO     | business.threads:run:36 - change dir: D:\LibCity\Bigscity-LibCity
2024-01-25 13:48:04.923 | INFO     | business.threads:run:51 - execute command: python run_model.py --exp_id 26238 --task map_matching --model HMMM --dataset 3_Seattle --saved_model True --train True --max_epoch 1 --gpu False --gpu_id 0
2024-01-25 13:48:04.944 | INFO     | common.utils:execute:99 - 命令执行进程启动，进程号: 25908
2024-01-25 13:48:14.958 | INFO     | common.utils:execute:104 - 实验已结束，状态码：1
2024-01-25 13:48:14.961 | ERROR    | common.utils:execute:114 - [ERROR] command: python run_model.py --exp_id 26238 --task map_matching --model HMMM --dataset 3_Seattle --saved_model True --train True --max_epoch 1 --gpu False --gpu_id 0; message: Traceback (most recent call last):
  File "run_model.py", line 36, in <module>
    run_model(task=args.task, model_name=args.model, dataset_name=args.dataset,
  File "D:\LibCity\Bigscity-LibCity\libcity\pipeline\pipeline.py", line 30, in run_model
    config = ConfigParser(task, model_name, dataset_name,
  File "D:\LibCity\Bigscity-LibCity\libcity\config\config_parser.py", line 25, in __init__
    self._load_default_config()
  File "D:\LibCity\Bigscity-LibCity\libcity\config\config_parser.py", line 115, in _load_default_config
    with open('./raw_data/{}/config.json'.format(self.config['dataset']), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: './raw_data/3_Seattle/config.json'

2024-01-25 13:48:14.995 | INFO     | business.threads:run:158 - execute completed! change path to: D:\LibCity\Bigscity-LibCity-WebTool-master\smartcityms_backend
2024-01-25 13:51:15.780 | INFO     | business.views:perform_create:93 - 已接受到文件，正在进行处理，文件名: Seattle.zip
2024-01-25 13:51:15.782 | INFO     | business.views:perform_create:116 - 存储到服务器上的临时文件路径：C:\Users\King.xx\AppData\Local\Temp\9bwm1wq_.upload.zip 正在把此文件复制到 raw_data 目录中：D:/LibCity/Bigscity-LibCity\raw_data\3_Seattle.zip
2024-01-25 13:51:15.797 | INFO     | business.views:perform_create:128 - 文件上传完毕，文件名: 3_Seattle
2024-01-25 13:52:43.032 | INFO     | business.threads:run:33 - start execute task, backup_dir: D:\LibCity\Bigscity-LibCity-WebTool-master\smartcityms_backend
2024-01-25 13:52:43.034 | INFO     | business.threads:run:36 - change dir: D:\LibCity\Bigscity-LibCity
2024-01-25 13:52:43.042 | INFO     | business.threads:run:51 - execute command: python run_model.py --exp_id 66769 --task map_matching --model HMMM --dataset 3_Seattle --saved_model False --train True --max_epoch 1 --gpu False --gpu_id 0
2024-01-25 13:52:43.063 | INFO     | common.utils:execute:99 - 命令执行进程启动，进程号: 22680
2024-01-25 13:52:45.888 | INFO     | business.handler:on_created:12 - 创建了新文件：D:/LibCity/Bigscity-LibCity\libcity\log\66769-HMMM-3_Seattle-Jan-25-2024_13-52-45.log
2024-01-25 13:52:45.890 | INFO     | business.handler:on_created:20 - set_log_file-日志文件名称: D:/LibCity/Bigscity-LibCity\libcity\log\66769-HMMM-3_Seattle-Jan-25-2024_13-52-45.log
2024-01-25 14:32:05.305 | INFO     | business.views:perform_create:93 - 已接受到文件，正在进行处理，文件名: seattle.zip
2024-01-25 14:32:05.306 | INFO     | business.views:dataset_duplication_handle:895 - 文件重复，文件路径：D:/LibCity/Bigscity-LibCity\raw_data\3_seattle.zip
2024-01-25 14:32:20.309 | INFO     | business.views:perform_create:93 - 已接受到文件，正在进行处理，文件名: Seattle - 副本.zip
2024-01-25 14:32:20.313 | INFO     | business.views:perform_create:116 - 存储到服务器上的临时文件路径：C:\Users\King.xx\AppData\Local\Temp\cgnob34x.upload.zip 正在把此文件复制到 raw_data 目录中：D:/LibCity/Bigscity-LibCity\raw_data\3_Seattle - 副本.zip
2024-01-25 14:32:20.358 | INFO     | business.views:perform_create:128 - 文件上传完毕，文件名: 3_Seattle - 副本
2024-01-25 14:32:20.362 | INFO     | business.views:perform_create:133 - 上传文件初步处理运行时间: 0.05250406265258789 s；下面进行geojson文件的生成
2024-01-25 14:32:21.175 | INFO     | business.save_geojson:__init__:652 - 当前配置数据集存储路径 raw_data 路径为：D:/LibCity/Bigscity-LibCity\raw_data\
2024-01-25 14:32:21.176 | INFO     | business.save_geojson:__init__:654 - 当前数据集名称为：3_Seattle - 副本
2024-01-25 14:32:21.178 | INFO     | business.save_geojson:__init__:656 - 当前数据集生成的 geojson 文件存储路径为：D:/LibCity/Bigscity-LibCity\raw_data\3_Seattle - 副本_geo_json
2024-01-25 14:32:21.180 | INFO     | business.save_geojson:__init__:661 - 当前数据集 config.json 文件路径为：D:/LibCity/Bigscity-LibCity\raw_data\3_Seattle - 副本\config.json
2024-01-25 14:32:21.183 | INFO     | business.save_geojson:__init__:677 - 数据集类型: trajectory
2024-01-25 14:32:22.583 | INFO     | business.save_geojson:_visualize_geo:970 - 加载的 geo 文件信息
2024-01-25 14:32:50.790 | INFO     | business.threads:run:196 - 3_Seattle - 副本 geojson文件生成完毕
2024-01-25 14:32:52.748 | DEBUG    | business.views:get_file_status:283 - after remove completed: []
2024-01-25 14:33:46.091 | INFO     | business.save_geojson:show_geo_view:242 - 尝试绘制D:/LibCity/Bigscity-LibCity\raw_data\3_Seattle - 副本_geo_json\Seattle_dyna.json文件的地理图象
2024-01-25 14:33:46.104 | INFO     | business.save_geojson:show_geo_view:258 - background select:https://webrd02.is.autonavi.com/appmaptile?lang=zh_en&size=1&scale=1&style=8&x={x}&y={y}&z={z} 
2024-01-25 14:33:46.169 | INFO     | business.save_geojson:show_geo_view:364 - D:/LibCity/Bigscity-LibCity\raw_data\3_Seattle - 副本_geo_json\Seattle_dyna.json文件的地理图象绘制成功
2024-01-25 14:33:46.178 | INFO     | business.threads:run:235 - 文件可视化完毕，文件状态：2
2024-01-25 14:33:46.189 | INFO     | business.threads:run:242 - 3_Seattle - 副本数据可视化处理完毕
2024-01-25 14:33:51.736 | DEBUG    | business.views:get_file_status:283 - after remove completed: []
2024-01-25 14:35:06.438 | INFO     | business.views:perform_create:93 - 已接受到文件，正在进行处理，文件名: shj.zip
2024-01-25 14:35:06.442 | INFO     | business.views:perform_create:116 - 存储到服务器上的临时文件路径：C:\Users\King.xx\AppData\Local\Temp\lhtb026s.upload.zip 正在把此文件复制到 raw_data 目录中：D:/LibCity/Bigscity-LibCity\raw_data\3_shj.zip
2024-01-25 14:35:06.469 | INFO     | business.views:perform_create:128 - 文件上传完毕，文件名: 3_shj
2024-01-25 14:35:06.473 | INFO     | business.views:perform_create:133 - 上传文件初步处理运行时间: 0.03560519218444824 s；下面进行geojson文件的生成
2024-01-25 14:35:07.110 | INFO     | business.save_geojson:__init__:652 - 当前配置数据集存储路径 raw_data 路径为：D:/LibCity/Bigscity-LibCity\raw_data\
2024-01-25 14:35:07.111 | INFO     | business.save_geojson:__init__:654 - 当前数据集名称为：3_shj
2024-01-25 14:35:07.112 | INFO     | business.save_geojson:__init__:656 - 当前数据集生成的 geojson 文件存储路径为：D:/LibCity/Bigscity-LibCity\raw_data\3_shj_geo_json
2024-01-25 14:35:07.113 | INFO     | business.save_geojson:__init__:661 - 当前数据集 config.json 文件路径为：D:/LibCity/Bigscity-LibCity\raw_data\3_shj\config.json
2024-01-25 14:35:07.115 | INFO     | business.save_geojson:__init__:677 - 数据集类型: trajectory
2024-01-25 14:35:08.504 | INFO     | business.save_geojson:_visualize_geo:970 - 加载的 geo 文件信息
2024-01-25 14:35:41.874 | INFO     | business.threads:run:196 - 3_shj geojson文件生成完毕
2024-01-25 14:35:46.521 | DEBUG    | business.views:get_file_status:283 - after remove completed: []
2024-01-25 14:35:52.172 | INFO     | business.save_geojson:show_geo_view:242 - 尝试绘制D:/LibCity/Bigscity-LibCity\raw_data\3_shj_geo_json\Seattle_dyna.json文件的地理图象
2024-01-25 14:35:52.197 | INFO     | business.save_geojson:show_geo_view:258 - background select:https://webrd02.is.autonavi.com/appmaptile?lang=zh_en&size=1&scale=1&style=8&x={x}&y={y}&z={z} 
2024-01-25 14:35:52.278 | INFO     | business.save_geojson:show_geo_view:364 - D:/LibCity/Bigscity-LibCity\raw_data\3_shj_geo_json\Seattle_dyna.json文件的地理图象绘制成功
2024-01-25 14:35:52.281 | INFO     | business.threads:run:235 - 文件可视化完毕，文件状态：2
2024-01-25 14:35:52.283 | INFO     | business.threads:run:242 - 3_shj数据可视化处理完毕
2024-01-25 14:35:57.214 | DEBUG    | business.views:get_file_status:283 - after remove completed: []
2024-01-25 14:45:31.913 | INFO     | business.views:perform_create:93 - 已接受到文件，正在进行处理，文件名: Seattle.zip
2024-01-25 14:45:31.913 | INFO     | business.views:perform_create:116 - 存储到服务器上的临时文件路径：C:\Users\King.xx\AppData\Local\Temp\co408mvj.upload.zip 正在把此文件复制到 raw_data 目录中：D:/LibCity/Bigscity-LibCity\raw_data\3_Seattle.zip
2024-01-25 14:45:31.930 | INFO     | business.views:perform_create:128 - 文件上传完毕，文件名: 3_Seattle
2024-01-25 14:45:31.930 | INFO     | business.views:perform_create:133 - 上传文件初步处理运行时间: 0.016136646270751953 s；下面进行geojson文件的生成
2024-01-25 14:45:32.429 | INFO     | business.save_geojson:__init__:652 - 当前配置数据集存储路径 raw_data 路径为：D:/LibCity/Bigscity-LibCity\raw_data\
2024-01-25 14:45:32.432 | INFO     | business.save_geojson:__init__:654 - 当前数据集名称为：3_Seattle
2024-01-25 14:45:32.432 | INFO     | business.save_geojson:__init__:656 - 当前数据集生成的 geojson 文件存储路径为：D:/LibCity/Bigscity-LibCity\raw_data\3_Seattle_geo_json
2024-01-25 14:45:32.432 | INFO     | business.save_geojson:__init__:661 - 当前数据集 config.json 文件路径为：D:/LibCity/Bigscity-LibCity\raw_data\3_Seattle\config.json
2024-01-25 14:45:32.435 | INFO     | business.save_geojson:__init__:677 - 数据集类型: trajectory
2024-01-25 14:45:33.392 | INFO     | business.save_geojson:_visualize_geo:970 - 加载的 geo 文件信息
2024-01-25 14:46:02.002 | INFO     | business.threads:run:196 - 3_Seattle geojson文件生成完毕
2024-01-25 14:46:03.718 | DEBUG    | business.views:get_file_status:283 - after remove completed: []
2024-01-25 14:48:35.042 | INFO     | business.views:perform_create:93 - 已接受到文件，正在进行处理，文件名: Chengdu_Taxi_Sample1.zip
2024-01-25 14:48:35.046 | INFO     | business.views:perform_create:116 - 存储到服务器上的临时文件路径：C:\Users\King.xx\AppData\Local\Temp\_hy17j26.upload.zip 正在把此文件复制到 raw_data 目录中：D:/LibCity/Bigscity-LibCity\raw_data\3_Chengdu_Taxi_Sample1.zip
2024-01-25 14:48:35.066 | INFO     | business.views:perform_create:128 - 文件上传完毕，文件名: 3_Chengdu_Taxi_Sample1
2024-01-25 14:48:35.070 | INFO     | business.views:perform_create:133 - 上传文件初步处理运行时间: 0.028067588806152344 s；下面进行geojson文件的生成
2024-01-25 14:48:35.343 | INFO     | business.save_geojson:__init__:652 - 当前配置数据集存储路径 raw_data 路径为：D:/LibCity/Bigscity-LibCity\raw_data\
2024-01-25 14:48:35.346 | INFO     | business.save_geojson:__init__:654 - 当前数据集名称为：3_Chengdu_Taxi_Sample1
2024-01-25 14:48:35.346 | INFO     | business.save_geojson:__init__:656 - 当前数据集生成的 geojson 文件存储路径为：D:/LibCity/Bigscity-LibCity\raw_data\3_Chengdu_Taxi_Sample1_geo_json
2024-01-25 14:48:35.346 | INFO     | business.save_geojson:__init__:661 - 当前数据集 config.json 文件路径为：D:/LibCity/Bigscity-LibCity\raw_data\3_Chengdu_Taxi_Sample1\config.json
2024-01-25 14:48:35.350 | INFO     | business.save_geojson:__init__:677 - 数据集类型: trajectory
2024-01-25 14:48:35.350 | ERROR    | business.save_geojson:__init__:704 - 文件当中没有geo文件, 异常信息：
2024-01-25 14:48:35.350 | ERROR    | business.save_geojson:visualize:729 - （trajectory）：文件当中没有geo文件或geo文件解析失败, 异常信息：list index out of range
2024-01-25 14:48:36.249 | INFO     | business.threads:run:196 - 3_Chengdu_Taxi_Sample1 geojson文件生成完毕
2024-01-25 14:48:40.133 | DEBUG    | business.views:get_file_status:283 - after remove completed: []
2024-01-25 14:49:11.507 | INFO     | business.threads:run:33 - start execute task, backup_dir: D:\LibCity\Bigscity-LibCity
2024-01-25 14:49:11.511 | INFO     | business.threads:run:36 - change dir: D:\LibCity\Bigscity-LibCity
2024-01-25 14:49:11.521 | INFO     | business.threads:run:51 - execute command: python run_model.py --exp_id 6480 --task eta --model DeepTTE --dataset 3_Chengdu_Taxi_Sample1 --saved_model True --train False --max_epoch 1 --gpu False --gpu_id 0
2024-01-25 14:49:11.552 | INFO     | common.utils:execute:99 - 命令执行进程启动，进程号: 13960
2024-01-25 14:49:15.435 | INFO     | business.handler:on_created:12 - 创建了新文件：D:/LibCity/Bigscity-LibCity\libcity\log\6480-DeepTTE-3_Chengdu_Taxi_Sample1-Jan-25-2024_14-49-15.log
2024-01-25 14:49:15.437 | INFO     | business.handler:on_created:20 - set_log_file-日志文件名称: D:/LibCity/Bigscity-LibCity\libcity\log\6480-DeepTTE-3_Chengdu_Taxi_Sample1-Jan-25-2024_14-49-15.log
2024-01-25 14:50:58.684 | INFO     | business.save_geojson:show_geo_view:242 - 尝试绘制D:/LibCity/Bigscity-LibCity\raw_data\3_Chengdu_Taxi_Sample1_geo_json\Chengdu_Taxi_Sample1_dyna.json文件的地理图象
2024-01-25 14:50:58.703 | INFO     | business.save_geojson:show_geo_view:258 - background select:https://mt.google.com/vt/lyrs=m&x={x}&y={y}&z={z}
2024-01-25 14:50:58.749 | INFO     | business.save_geojson:show_geo_view:364 - D:/LibCity/Bigscity-LibCity\raw_data\3_Chengdu_Taxi_Sample1_geo_json\Chengdu_Taxi_Sample1_dyna.json文件的地理图象绘制成功
2024-01-25 14:50:58.749 | INFO     | business.threads:run:235 - 文件可视化完毕，文件状态：2
2024-01-25 14:50:58.749 | INFO     | business.threads:run:242 - 3_Chengdu_Taxi_Sample1数据可视化处理完毕
2024-01-25 14:51:03.748 | DEBUG    | business.views:get_file_status:283 - after remove completed: []
2024-01-25 17:27:56.250 | INFO     | common.utils:execute:104 - 实验已结束，状态码：0
2024-01-25 17:27:56.256 | INFO     | common.utils:execute:111 - [SUCCESS] python run_model.py --exp_id 66769 --task map_matching --model HMMM --dataset 3_Seattle --saved_model False --train True --max_epoch 1 --gpu False --gpu_id 0
2024-01-25 17:27:56.258 | INFO     | business.threads:rename_result:76 - evaluate_cache文件夹下文件按照创建时间排序: ['2024_01_25_17_27_50_HMMM_3_Seattle.csv', '2024_01_25_17_27_50_HMMM_3_Seattle_result.json', '2024_01_25_17_27_50_HMMM_3_Seattle']
2024-01-25 17:27:56.291 | INFO     | business.show.map_matching_show:matching_result_map:42 - The result json path is: D:/LibCity/Bigscity-LibCity\libcity\cache\66769\evaluate_cache\18_HMMM_3_Seattle_result.json
2024-01-25 17:27:56.293 | INFO     | business.show.map_matching_show:matching_result_map:43 - The dataset json path is: D:/LibCity/Bigscity-LibCity\raw_data\3_Seattle_geo_json\Seattle_dyna.json
2024-01-25 17:27:56.304 | INFO     | common.utils:return_location:316 - 地图location: [-122.3206, 47.61123333]
2024-01-25 17:27:56.344 | INFO     | business.show.map_matching_show:render_to_map:71 - The task result file was generated successfully, html path: D:/LibCity/Bigscity-LibCity-WebTool-master/smartcityms_front/dist/3_Seattle_66769_result.html
